export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const QUOTE_LOAD = "QUOTE_LOAD";
export const FIELD_LOAD_START = "FIELD_LOAD_START";
export const FIELD_LOAD_SUCCESS = "FIELD_LOAD_SUCCESS";
export const FIELD_LOAD_ERROR = "FIELD_LOAD_ERROR";
export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";
