export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const QUOTE_LOAD_START = "QUOTE_LOAD_START";
export const QUOTE_LOAD_SUCCESS = "QUOTE_LOAD_SUCCESS";
export const QUOTE_LOAD_ERROR = "QUOTE_LOAD_ERROR";

export const PROFILE_LOAD_START = "PROFILE_LOAD_START";
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS";
export const PROFILE_LOAD_ERROR = "PROFILE_LOAD_ERROR";

export const FIELD_ACTION_START = "FIELD_ACTION_START";
export const FIELD_ACTION_ERROR = "FIELD_ACTION_ERROR";
export const FIELD_EDIT_SUCCESS = "FIELD_EDIT_SUCCESS";
export const FIELD_LOAD_SUCCESS = "FIELD_LOAD_SUCCESS";
export const FIELD_ADD_SUCCESS = "FIELD_ADD_SUCCESS";
export const FIELD_DELETE_SUCCESS = "FIELD_DELETE_SUCCESS";

export const GOAL_ACTION_START = "GOAL_ACTION_START";
export const GOAL_ACTION_ERROR = "GOAL_ACTION_ERROR";
export const GOAL_EDIT_SUCCESS = "GOAL_EDIT_SUCCESS";
export const GOAL_LOAD_SUCCESS = "GOAL_LOAD_SUCCESS";
export const GOAL_ADD_SUCCESS = "GOAL_ADD_SUCCESS";
export const GOAL_DELETE_SUCCESS = "GOAL_DELETE_SUCCESS";
export const GOAL_PARTNERS_SUCCESS = "GOAL_PARTNERS_SUCCESS";

export const ACTION_ACTION_START = "ACTION_ACTION_START";
export const ACTION_ACTION_ERROR = "ACTION_ACTION_ERROR";
export const ACTION_EDIT_SUCCESS = "ACTION_EDIT_SUCCESS";
export const ACTION_LOAD_SUCCESS = "ACTION_LOAD_SUCCESS";
export const TODAYACTION_LOAD_SUCCESS = "TODAYACTION_LOAD_SUCCESS";
export const ACTION_ADD_SUCCESS = "ACTION_ADD_SUCCESS";
export const ACTION_DELETE_SUCCESS = "ACTION_DELETE_SUCCESS";

export const PROMODORO_ACTION_START = "PROMODORO_ACTION_START";
export const PROMODORO_ACTION_ERROR = "PROMODORO_ACTION_ERROR";
export const PROMODORO_LOAD_SUCCESS = "PROMODORO_LOAD_SUCCESS";
export const PROMODORO_UPDATE_SUCCESS = "PROMODORON_UPDATE_SUCCESS";
export const PROMODORO_ADD_SUCCESS = "PROMODORO_ADD_SUCCESS";

export const CHAT_ACTION_START = "CHAT_ACTION_START";
export const CHAT_ACTION_ERROR = "CHAT_ACTION_ERROR";
export const CHAT_ADD_SUCCESS = "CHAT_ADD_SUCCESS";
export const CHAT_LOAD_SUCCESS = "CHAT_LOAD_SUCCESS";
export const CHAT_RESET_NOTIF = "CHAT_RESET_NOTIF";

export const PAYMENT_ACTION_START = "PAYMENT_ACTION_START";
export const PAYMENT_ACTION_ERROR = "PAYMENT_ACTION_ERROR";
export const PAYMENT_ACTION_SUCCESS = "PAYMENT_ACTION_SUCCESS";

export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";
