export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const QUOTE_LOAD_START = "QUOTE_LOAD_START";
export const QUOTE_LOAD_SUCCESS = "QUOTE_LOAD_SUCCESS";
export const QUOTE_LOAD_ERROR = "QUOTE_LOAD_ERROR";

export const FIELD_ACTION_START = "FIELD_ACTION_START";
export const FIELD_ACTION_ERROR = "FIELD_ACTION_ERROR";
export const FIELD_EDIT_SUCCESS = "FIELD_EDIT_SUCCESS";
export const FIELD_LOAD_SUCCESS = "FIELD_LOAD_SUCCESS";
export const FIELD_ADD_SUCCESS = "FIELD_ADD_SUCCESS";
export const FIELD_DELETE_SUCCESS = "FIELD_DELETE_SUCCESS";

export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";
